services:
  srt:
    container_name: srt
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8282:8282/udp"
      - "8181:8181/udp"
      - "5000:5000/udp"
    command: >
      bash -c "
      /opt/srtla/srtla_rec 5000 127.0.0.1 8282 & 
      /opt/srt-live-server/bin/sls -c /opt/srt-live-server/sls.conf
      "

  nginx-rtmp:
    container_name: nginx-rtmp
    build:
      context: .
      dockerfile: Dockerfile.rtmp
    ports:
      - "1935:1935"    # RTMP port
      - "80:80"        # HTTP port (though not used in config)
