services:
  srt:
    container_name: srt
    privileged: "true"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8282:8282/udp"
      - "8181:8181/udp"
      - "5000:5000/udp"
    command: >
      bash -c "
      /opt/srtla/srtla_rec 5000 127.0.0.1 8282 & 
      /opt/srt-live-server/bin/sls -c /opt/srt-live-server/sls.conf
      "
